# Generated by Django 4.2 on 2023-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_services_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='whyus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomber', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=300)),
            ],
        ),
    ]
