# Generated by Django 4.2 on 2023-05-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_whyus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pricing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TextOffPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li', models.CharField(max_length=200)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.pricing')),
            ],
        ),
    ]
