# Generated by Django 4.2 on 2023-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_pricing_textoffpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
